/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "tests/notation_test.check" instead.
 */

#include <check.h>
#include <math.h>
#include <stdio.h>

#include "../credit_calc.h"
#include "../deposit_calc.h"
#include "../polish_notation.h"
#include "../s21_smart_calc.h"

#define SIZE_ARRAY 255

START_TEST(one_operator) {
  double a = 13.14;
  double b = 45.01;
  double result = 0., expected_result = 0.;
  char lexeme[SIZE_ARRAY] = {0};
  int error = 0;

  sprintf(lexeme, "%lf+%lf", a, b);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = a + b;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "%lf-%lf", a, b);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = a - b;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "%lf*%lf", a, b);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = a * b;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "%lf/%lf", a, b);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = a / b;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "%lfmod%lf", a, b);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = fmod(a, b);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "%lf^%lf", 0.105, 2.002);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = pow(0.105, 2.002);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "sin(%lf)", a);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = sin(a);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "cos(%lf)", a);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = cos(a);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "tan(%lf)", a);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = tan(a);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  a = 0.7;
  b = 0.499999;
  sprintf(lexeme, "asin(%lf)", a);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = asin(a);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "acos(%lf)", b);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = acos(b);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "atan(%lf)", a);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = atan(a);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "sqrt(%lf)", b);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = sqrt(b);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "ln(%lf)", a);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = log(a);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "log(%lf)", b);
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = log10(b);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);
}
END_TEST

START_TEST(several_operators) {
  char lexeme[SIZE_ARRAY] = "1+2-3.2*7.008/2*2-2.5";
  double result = 0., expected_result = 0.;
  int error = 0;

  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = 1 + 2 - 3.2 * 7.008 / 2 * 2 - 2.5;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "1.0001*29999.555-456/1.23456789+5*9/9*9+6-7");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result =
      1.0001 * 29999.555 - 456 / 1.23456789 + 5 * 9 / 9 * 9 + 6 - 7;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "1.+1+1+1+1+1+1+1-1-1./11*1-1/1-11-1*1/1*1/1-1/1*1+1-1/1*1");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = 1. + 1 + 1 + 1 + 1 + 1 + 1 + 1 - 1 - 1. / 11 * 1 - 1 / 1 -
                    11 - 1 * 1 / 1 * 1 / 1 - 1 / 1 * 1 + 1 - 1 / 1 * 1;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(
      lexeme,
      "0.0001*12345.6789*12345.921-568.3245687+78.1234567*0.0000001/0.020201");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = 0.0001 * 12345.6789 * 12345.921 - 568.3245687 +
                    78.1234567 * 0.0000001 / 0.020201;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);
}
END_TEST

START_TEST(unary_plus_and_minus) {
  char lexeme[SIZE_ARRAY] = "-1+2-3.2*7.008/2*2-2.5";
  double result = 0., expected_result = 0.;
  int error = 0;

  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = -1 + 2 - 3.2 * 7.008 / 2 * 2 - 2.5;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "+1.0001*29999.555-456/1.23456789+5*9/9*9+6-7");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result =
      +1.0001 * 29999.555 - 456 / 1.23456789 + 5 * 9 / 9 * 9 + 6 - 7;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "-1.0001*(+29999.555)-(-456.)/(+1.23456789)+(-5)*9/9*9+6-7");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = -1.0001 * (+29999.555) - (-456.) / (+1.23456789) +
                    (-5) * 9 / 9 * 9 + 6 - 7;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme,
          "-1.0001*(-29999.555)-(-456.)/(-1.234789)+(-5)*(-9)/(-9)*(-9./"
          "(-6.)+6.-7)");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = -1.0001 * (-29999.555) - (-456.) / (-1.234789) +
                    (-5) * (-9) / (-9) * (-9. / (-6.) + 6. - 7);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);
}
END_TEST

START_TEST(brackets) {
  char lexeme[SIZE_ARRAY] = "(((((((5+1)*2)*2)*2)*2)))";
  double result = 0., expected_result = 0.;
  int error = 0;

  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = (((((((5. + 1.) * 2.) * 2.) * 2.) * 2.)));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme, "(((((((5.+1.)*2.)*2.)*2.)*2.)))*((1.+2.)-1)-(((((1)))))");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result =
      (((((((5. + 1.) * 2.) * 2.) * 2.) * 2.))) * ((1. + 2.) - 1) - (((((1)))));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme,
          "(-(-(-(-(-(-(5.+1.)*2.)*2.)*2.)*2.)))*((1.+2.)-1)-(((((1)))))");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result =
      (-(-(-(-(-(-(5. + 1.) * 2.) * 2.) * 2.) * 2.))) * ((1. + 2.) - 1) -
      (((((1)))));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  result = 0.;
  sprintf(lexeme, "()");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = 0.;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  result = 0.;
  sprintf(lexeme, "((()))");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = 0.;
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);
}
END_TEST

START_TEST(several_trigonometric_pow) {
  char lexeme[SIZE_ARRAY] = "sin(cos(tan(0.0001)))";
  double result = 0., expected_result = 0.;
  int error = 0;

  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = sin(cos(tan(0.0001)));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme,
          "sin(cos(tan(0.0001)))*tan(sin(-1.*0.2))+cos(atan(0.98/2-0.0001))");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = sin(cos(tan(0.0001))) * tan(sin(-1. * 0.2)) +
                    cos(atan(0.98 / 2 - 0.0001));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme,
          "sin(cos(tan(0.0001)))*tan(sin(-1.*0.2))+cos(atan(0.98/"
          "2-0.0001))+sin(0)+acos(1)+asin(0.000003)");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = sin(cos(tan(0.0001))) * tan(sin(-1. * 0.2)) +
                    cos(atan(0.98 / 2 - 0.0001)) + sin(0) + acos(1) +
                    asin(0.000003);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme,
          "2.^(sin(cos(tan(0.0001)))*tan(sin(-1.*0.2)))+0.2^(cos(atan(0.98/"
          "2-0.0001))+sin(0)+acos(1)+asin(0.000003))");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = pow(2., (sin(cos(tan(0.0001))) * tan(sin(-1. * 0.2)))) +
                    pow(0.2, (cos(atan(0.98 / 2 - 0.0001)) + sin(0) + acos(1) +
                              asin(0.000003)));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);
}
END_TEST

START_TEST(several_another_functions) {
  char lexeme[SIZE_ARRAY] = "ln(1.2mod0.00345+sqrt(3.1415*(-log(0.12300001))))";
  double result = 0., expected_result = 0.;
  int error = 0;

  error = count_lexeme(lexeme, 0., false, &result);
  expected_result =
      log(fmod(1.2, 0.00345) + sqrt(3.1415 * (-log10(0.12300001))));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  sprintf(lexeme,
          "-ln(1.2mod(sin(0.005)*0.00345)+sqrt(3.1415*(-log(0.12300001))))");
  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = -log(fmod(1.2, sin(0.005) * 0.00345) +
                         sqrt(3.1415 * (-log10(0.12300001))));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);
}
END_TEST

START_TEST(aboba_all) {
  char lexeme[SIZE_ARRAY] =
      "-sin(-0.2365/"
      "atan(1.002)+acos(0.141528)^(3.1415))+(-log(10*cos(-sqrt(2.3-3.7/"
      "89)+1415.)))/ln(3.321+atan(-3mod4))";
  double result = 0., expected_result = 0.;
  int error = 0;

  error = count_lexeme(lexeme, 0., false, &result);
  expected_result = -sin(-0.2365 / atan(1.002) + pow(acos(0.141528), 3.1415)) +
                    (-log10(10 * cos(-sqrt(2.3 - 3.7 / 89) + 1415.))) /
                        log(3.321 + atan(fmod(-3., 4.)));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);
}
END_TEST

START_TEST(hard_x_test) {
  char lexeme[SIZE_ARRAY] =
      "-sin(-0.2365*x/"
      "atan(1.002)+acos(0.141528)^(3.1415))+(-log(10*cos(-sqrt(2.3-3.7/"
      "89)+1415.)))/ln(3.321+atan(-3mod4))";
  double result = 0., expected_result = 0.;
  int error = 0;
  double x = 0.1346;

  error = count_lexeme(lexeme, x, true, &result);
  expected_result =
      -sin(-0.2365 * x / atan(1.002) + pow(acos(0.141528), 3.1415)) +
      (-log10(10 * cos(-sqrt(2.3 - 3.7 / 89) + 1415.))) /
          log(3.321 + atan(fmod(-3., 4.)));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  x = -0.000001;
  sprintf(lexeme,
          "-sin(-0.2365*x/atan(1.002)+acos(0.141528)^(3.1415))+x-x*x/"
          "(-log(10*cos(-sqrt(2.3-3.7/89)+1415.)))/ln(3.321+atan(-3mod4))");
  error = count_lexeme(lexeme, x, true, &result);
  expected_result =
      -sin(-0.2365 * x / atan(1.002) + pow(acos(0.141528), 3.1415)) + x -
      x * x / (-log10(10 * cos(-sqrt(2.3 - 3.7 / 89) + 1415.))) /
          log(3.321 + atan(fmod(-3., 4.)));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  x = 0.0000005;
  sprintf(lexeme,
          "-sin(-0.2365*x/atan(1.002)+acos(0.141528)^(3.1415))+x-x*x/"
          "(-log(10*cos(-sqrt(2.3-3.7/89)+1415.)))/ln(3.321+atan(-3mod4))");
  error = count_lexeme(lexeme, x, true, &result);
  expected_result =
      -sin(-0.2365 * x / atan(1.002) + pow(acos(0.141528), 3.1415)) + x -
      x * x / (-log10(10 * cos(-sqrt(2.3 - 3.7 / 89) + 1415.))) /
          log(3.321 + atan(fmod(-3., 4.)));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  x = 4815.162342;
  sprintf(lexeme,
          "-sin(-0.2365*x/atan(1.002)+acos(0.141528)^(3.1415))+x-x*x/"
          "(-log(10*cos(-sqrt(2.3-3.7/89)+1415.)))/ln(3.321+atan(-3mod4))");
  error = count_lexeme(lexeme, x, true, &result);
  expected_result =
      -sin(-0.2365 * x / atan(1.002) + pow(acos(0.141528), 3.1415)) + x -
      x * x / (-log10(10 * cos(-sqrt(2.3 - 3.7 / 89) + 1415.))) /
          log(3.321 + atan(fmod(-3., 4.)));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);

  x = 0.;
  sprintf(lexeme,
          "-sin(-0.2365*x/atan(1.002)+acos(0.141528)^(3.1415))+x-x*x/"
          "(-log(10*cos(-sqrt(2.3-3.7/89)+1415.)))/ln(3.321+atan(-3mod4))");
  error = count_lexeme(lexeme, x, true, &result);
  expected_result =
      -sin(-0.2365 * x / atan(1.002) + pow(acos(0.141528), 3.1415)) + x -
      x * x / (-log10(10 * cos(-sqrt(2.3 - 3.7 / 89) + 1415.))) /
          log(3.321 + atan(fmod(-3., 4.)));
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, expected_result, 0.0000001);
}
END_TEST

START_TEST(error_polish_notation) {
  char lexeme[SIZE_ARRAY] = "1+2-*3.2*+7.008/2*2-2.5";
  double result = 0.;
  int error = 0;

  error = count_lexeme(lexeme, 0., false, &result);
  ck_assert_int_eq(ERROR_POLISH, error);

  sprintf(lexeme, "(1.+2.)(1)");
  error = count_lexeme(lexeme, 0., false, &result);
  ck_assert_int_eq(ERROR_POLISH, error);

  sprintf(lexeme, "1+2.+45+2.3.-1");
  error = count_lexeme(lexeme, 0., false, &result);
  ck_assert_int_eq(ERROR_POLISH, error);

  sprintf(lexeme, "1+2.+45+.3-1");
  error = count_lexeme(lexeme, 0., false, &result);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, 1 + 2. + 45 + .3 - 1, 0.0000001);
}
END_TEST

START_TEST(error_argument_requaired) {
  char lexeme[SIZE_ARRAY] = "1+2*3.2*x+7.008/2*2-2.5";
  double result = 0.;
  int error = 0;

  error = count_lexeme(lexeme, 0., false, &result);
  ck_assert_int_eq(ARGUMENT_REQUIRED, error);

  sprintf(lexeme, "3.+4.");
  error = count_lexeme(lexeme, 1., true, &result);
  ck_assert_int_eq(0, error);
  ck_assert_ldouble_eq_tol(result, 7., 0.0000001);
}
END_TEST

START_TEST(ipoteka) {
  credit test = {12345600., 132, 8.5, true, 0, 0, 0, 0, 0};

  credit_calc(&test);
  ck_assert_double_eq_tol(test.monthly_payment, 144275.52, 1);
  ck_assert_double_eq_tol(test.interest_charges, 6698768.64, 1);
  ck_assert_double_eq_tol(test.total_payment, 19044368.64, 1);

  test.amount = 5600000.;
  test.duration = 96;
  test.rate = 9.6;

  credit_calc(&test);
  ck_assert_double_eq_tol(test.monthly_payment, 83794.68, 1);
  ck_assert_double_eq_tol(test.interest_charges, 2444289.28, 1);
  ck_assert_double_eq_tol(test.total_payment, 8044289.28, 1);

  test.annuity = false;

  credit_calc(&test);
  ck_assert_double_eq_tol(test.payment_diff_first, 103133.33, 1);
  ck_assert_double_eq_tol(test.payment_diff_last, 58800., 1);
  ck_assert_double_eq_tol(test.interest_charges, 2172800., 1);
  ck_assert_double_eq_tol(test.total_payment, 7772800., 1);
}
END_TEST

START_TEST(pensionnii_fond) {
  deposit test = {45000., 48, 6.3, 13., 0, 0, 0, 0, true, 1, 0, 0, 0};

  deposit_calc(&test);
  ck_assert_double_eq_tol(test.result_charges, 12858.67, 1);
  ck_assert_double_eq_tol(test.reuslt_amount, 57858.67, 1);

  test.duration = 24;
  test.capitalization = false;

  deposit_calc(&test);
  ck_assert_double_eq_tol(test.result_charges, 5669.98, 1);
  ck_assert_double_eq_tol(test.reuslt_amount, 45000., 1);

  test.replenishment = 12;
  test.replenishment_amount = 1000.;
  test.withdrawal = 12;
  test.withdrawal_amount = 1000.;

  deposit_calc(&test);
  ck_assert_double_eq_tol(test.result_charges, 5669.98, 1);
  ck_assert_double_eq_tol(test.reuslt_amount, 45000., 1);

  test.payment_period = 0;

  deposit_calc(&test);
  ck_assert_double_eq_tol(test.result_charges, 5670., 1);
  ck_assert_double_eq_tol(test.reuslt_amount, 45000., 1);
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("test_without_argument");
  TCase *tc1_1 = tcase_create("simple_tests");
  TCase *tc1_2 = tcase_create("harder_tests");
  Suite *s2 = suite_create("test_with_argument");
  TCase *tc2_1 = tcase_create("test_with_argument");
  Suite *s3 = suite_create("test_errors");
  TCase *tc3_1 = tcase_create("error_check");
  Suite *s4 = suite_create("test_credit_and_deposit");
  TCase *tc4_1 = tcase_create("credit_calc");
  TCase *tc4_2 = tcase_create("deposit_calc");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);
  tcase_add_test(tc1_1, one_operator);
  tcase_add_test(tc1_1, several_operators);
  tcase_add_test(tc1_1, unary_plus_and_minus);
  tcase_add_test(tc1_1, brackets);
  suite_add_tcase(s1, tc1_2);
  tcase_add_test(tc1_2, several_trigonometric_pow);
  tcase_add_test(tc1_2, several_another_functions);
  tcase_add_test(tc1_2, aboba_all);
  suite_add_tcase(s2, tc2_1);
  tcase_add_test(tc2_1, hard_x_test);
  suite_add_tcase(s3, tc3_1);
  tcase_add_test(tc3_1, error_polish_notation);
  tcase_add_test(tc3_1, error_argument_requaired);
  suite_add_tcase(s4, tc4_1);
  tcase_add_test(tc4_1, ipoteka);
  suite_add_tcase(s4, tc4_2);
  tcase_add_test(tc4_2, pensionnii_fond);

  srunner_add_suite(sr, s2);
  srunner_add_suite(sr, s3);
  srunner_add_suite(sr, s4);

  srunner_run_all(sr, CK_VERBOSE);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
